[WIP] Port LFS functions from old metastore
datopian/metastore-lib-js pull request #12
Opened 2021-01-12 16:02 UTC by risenW

This pull fixes #11

2021-01-14 15:33 UTC, cotts requested changes
Review comments

@risenW  : `git_lfs_helper.js` , `git_api_helper.js` and the test files should be camelCase named instead snake_case

2021-01-14 15:33 UTC, cotts commented on src/backend/github.js
> +          let filesToUpload = { metadata: metadata, readMe: readMe }
you can use `const` here

2021-01-14 15:33 UTC, cotts commented on src/backend/github.js
>            let metadata = repo.metadata
you can use destructing over here 
```
const { author, metadata } = repo
```

2021-01-15 10:01 UTC, risenW commented on src/backend/github.js
>            let metadata = repo.metadata
True, thanks

2021-01-15 11:41 UTC, cotts approved these changes
LGTM 🥇

2021-01-15 11:41 UTC, merged